# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzsxRaxeXhq8pr_1Olwufr77TFpp3Q58
"""

from flask import Flask, render_template_string, request, redirect, url_for, flash

app = Flask(__name__)
app.secret_key = 'university_secret_key'  # Needed for flashing messages

# --- 1. MOCK DATABASE ---
# Updated: All 'enrolled' counts are initialized to 0.
courses = [
    {"id": 101, "code": "AM2301", "name": "Applied Mathematics ||| ", "prof": "Mrs Shrawani Mitkari", "credits": 4, "capacity": 30, "enrolled": 0},
    {"id": 102, "code": "CSE2304", "name": "Data Structures", "prof": "Mrs Monalisa Hati", "credits": 3, "capacity": 50, "enrolled": 0},
    {"id": 103, "code": "FL-301", "name": "Foreign Language", "prof": "Mrs Surekha Athawade", "credits": 4, "capacity": 40, "enrolled": 0},
    {"id": 104, "code": "PHY-101", "name": "Quantum Mechanics", "prof": "Dr. Feynman", "credits": 3, "capacity": 25, "enrolled": 0},
    {"id": 105, "code": "ENG-101", "name": "Technical Writing", "prof": "Prof. Hemingway", "credits": 2, "capacity": 60, "enrolled": 0},
    {"id": 106, "code": "HIST-200", "name": "World History", "prof": "Dr. Howard", "credits": 3, "capacity": 30, "enrolled": 0}
]

# Track which courses the current user has registered for
my_schedule = []

# --- 2. HTML TEMPLATE ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UniReg | Course Registration</title>
    <!-- Using Bootstrap CSS for instant styling -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; }
        .navbar { background-color: #2c3e50; }
        .card { border: none; box-shadow: 0 4px 6px rgba(0,0,0,0.1); transition: transform 0.2s; }
        .card:hover { transform: translateY(-5px); }
        .status-full { color: #dc3545; font-weight: bold; }
        .status-open { color: #198754; font-weight: bold; }
        .btn-register { width: 100%; }
    </style>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">🏛️ University Portal</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="navbar-text text-white">Student: <strong>Guest User</strong></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">

    <!-- Flash Messages (Errors/Success) -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="row">
        <!-- LEFT COLUMN: Available Courses -->
        <div class="col-md-8">
            <h3 class="mb-3">🎓 Available Courses</h3>
            <div class="row">
                {% for course in courses %}
                <div class="col-md-6 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.code }}: {{ course.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ course.prof }}</h6>
                            <p class="card-text">
                                <strong>Credits:</strong> {{ course.credits }}<br>
                                <strong>Status:</strong>
                                <span class="{{ 'status-full' if course.enrolled >= course.capacity else 'status-open' }}">
                                    {{ course.enrolled }} / {{ course.capacity }} Seats
                                </span>
                            </p>
                        </div>
                        <div class="card-footer bg-white">
                            {% if course.id in my_schedule %}
                                <button class="btn btn-secondary btn-register" disabled>Enrolled ✅</button>
                            {% elif course.enrolled >= course.capacity %}
                                <button class="btn btn-outline-danger btn-register" disabled>Class Full 🚫</button>
                            {% else %}
                                <form action="/register/{{ course.id }}" method="POST">
                                    <button type="submit" class="btn btn-primary btn-register">Register Now</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- RIGHT COLUMN: My Schedule -->
        <div class="col-md-4">
            <div class="card p-3">
                <h4 class="mb-3">📅 My Schedule</h4>
                {% if my_schedule_details %}
                    <ul class="list-group list-group-flush">
                        {% for item in my_schedule_details %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div>
                                    <strong>{{ item.code }}</strong><br>
                                    <small>{{ item.name }}</small>
                                </div>
                                <span class="badge bg-primary rounded-pill">{{ item.credits }} Cr</span>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="mt-3 pt-3 border-top">
                        <h5>Total Credits: {{ total_credits }}</h5>
                    </div>
                {% else %}
                    <div class="alert alert-info">You haven't registered for any classes yet.</div>
                {% endif %}

                <div class="mt-4">
                    <form action="/reset" method="POST">
                        <button class="btn btn-outline-secondary btn-sm w-100">Reset Schedule</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
"""

# --- 3. ROUTES & LOGIC ---

@app.route('/')
def home():
    # Retrieve full details of courses the student is enrolled in
    my_schedule_details = [c for c in courses if c['id'] in my_schedule]
    total_credits = sum(c['credits'] for c in my_schedule_details)

    return render_template_string(
        HTML_TEMPLATE,
        courses=courses,
        my_schedule=my_schedule,
        my_schedule_details=my_schedule_details,
        total_credits=total_credits
    )

@app.route('/register/<int:course_id>', methods=['POST'])
def register(course_id):
    # Find the course object
    course = next((c for c in courses if c['id'] == course_id), None)

    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for('home'))

    # Validation Logic
    if course_id in my_schedule:
        flash(f"You are already registered for {course['code']}.", "warning")
    elif course['enrolled'] >= course['capacity']:
        flash(f"Sorry, {course['code']} is currently full.", "danger")
    else:
        # Success Logic
        course['enrolled'] += 1
        my_schedule.append(course_id)
        flash(f"Successfully registered for {course['name']}!", "success")

    return redirect(url_for('home'))

@app.route('/reset', methods=['POST'])
def reset():
    # Logic to drop all classes (for testing purposes)
    global my_schedule
    for course_id in my_schedule:
        course = next((c for c in courses if c['id'] == course_id), None)
        if course:
            course['enrolled'] -= 1
    my_schedule = []
    flash("Schedule cleared.", "info")
    return redirect(url_for('home'))

if __name__ == '__main__':
    app.run(debug=True)
